In [299]:
#Atividades:

# 1.
# - Ler os dados fornecidos;
# - Tratar valores ausentes (dados faltantes);
# - Organizar os dados para análise.

# 2. Geração de Estatísticas Básicas
# Calcular as médias de temperatura, nível do rio e NDVI.

# 3. Visualização de Dados
# Criar ao menos dois gráficos (ex: evolução da temperatura, nível do rio ou NDVI ao longo do tempo)

In [300]:
import pandas

# comando para ler um arquivo:  pandas.read_[tipo do arquivo]("[nome do arquivo]")
# neste caso o comando é: pandas.read_csv("dados_pantanal.csv")

tabela = pandas.read_csv("dados_pantanal.csv")

# comando para mostrar tabelas de maneira "bonitinha": display([base de dados, em questão, que foi lida com pandas.read])
# neste caso o comando é: display(tabela)

display(tabela)

         data  temperatura_c  nivel_rio_m  ndvi
0  2025-01-01           32.5          4.2  0.65
1  2025-01-02           33.1          4.3  0.67
2  2025-01-03           34.0          NaN  0.66
3  2025-01-04           35.2          4.5   NaN
4  2025-01-05           36.0          4.7  0.70
5  2025-01-06           35.5          4.8  0.72
6  2025-01-07           34.8          NaN  0.71
7  2025-01-08           33.9          4.6  0.69
8  2025-01-09           32.7          4.4   NaN
9  2025-01-10           31.8          4.3  0.66

In [301]:
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           10 non-null     str
 1   temperatura_c  10 non-null     float64
 2   nivel_rio_m    8 non-null      float64
 3   ndvi           8 non-null      float64
dtypes: float64(3), str(1)
memory usage: 452.0 bytes

None

In [302]:
# Para preencher os valores vazios estimando o valor com base nos vizinhos
# Use o comando [Base de dados lida anteriormente].interpolate()
# Nesse caso seria: tabela = tabela.interpolate()
# Porém, para o código rodar perfeitamente, é necessário um ajuste. 
# Pois o Pandas não sabe calcular a "média" entre textos, então é necessário ignorar a coluna de data na hora de interpolar ou focar apenas nas colunas numéricas.

# 1. Transformamos a coluna data em um formato que o Pandas entenda como tempo
# A coluna "data" ta em formato de string, o que resulta em um erro
# Use o comando pandas.to_datetime([base de dados lida anteriormente]["[coluna de datas da tabela]"])


tabela["data"] = pandas.to_datetime(tabela["data"])

#apos isso, a coluna "data" será do Dtype -exibido no display(tabela.info())- "datetime64". Como é um formato de tempo, o Pandas irá ignorar essa coluna durante o cálculo matemático, evitando o erro

# 2. Fazemos a interpolação apenas nas colunas que são números
tabela = tabela.interpolate()

# 3. Exibimos a tabela pronta
display(tabela)
display(tabela.info())

        data  temperatura_c  nivel_rio_m   ndvi
0 2025-01-01           32.5          4.2  0.650
1 2025-01-02           33.1          4.3  0.670
2 2025-01-03           34.0          4.4  0.660
3 2025-01-04           35.2          4.5  0.680
4 2025-01-05           36.0          4.7  0.700
5 2025-01-06           35.5          4.8  0.720
6 2025-01-07           34.8          4.7  0.710
7 2025-01-08           33.9          4.6  0.690
8 2025-01-09           32.7          4.4  0.675
9 2025-01-10           31.8          4.3  0.660

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           10 non-null     datetime64[us]
 1   temperatura_c  10 non-null     float64
 2   nivel_rio_m    10 non-null     float64
 3   ndvi           10 non-null     float64
dtypes: datetime64[us](1), float64(3)
memory usage: 452.0 bytes

None

In [303]:
#################       Renomeando as colunas      #####################

#Renomearemos as colunas para aparecerem os "nomes bonitos" nos gráficos


# Renomeando via código:
tabela = tabela.rename(columns={
    "data": "Data",
    "temperatura_c": "Temperatura (°C)",
    "nivel_rio_m": "Nível do rio (m)",
    "ndvi": "Índice de Vegetação (NDVI)"
})


display(tabela)

        Data  Temperatura (°C)  Nível do rio (m)  Índice de Vegetação (NDVI)
0 2025-01-01              32.5               4.2                       0.650
1 2025-01-02              33.1               4.3                       0.670
2 2025-01-03              34.0               4.4                       0.660
3 2025-01-04              35.2               4.5                       0.680
4 2025-01-05              36.0               4.7                       0.700
5 2025-01-06              35.5               4.8                       0.720
6 2025-01-07              34.8               4.7                       0.710
7 2025-01-08              33.9               4.6                       0.690
8 2025-01-09              32.7               4.4                       0.675
9 2025-01-10              31.8               4.3                       0.660

In [ ]:
##################      Esboçando em gráficos      #####################

#Obs: Para isso será utilizada a biblioteca plotly

import plotly.express as px  # <-- Sempre importe a biblioteca plotly assim

#comando para criar gráficos: 
# px.[tipo de gráfico que você quer criar]([Base de dados lida anteriormente], x="coluna que voce quer que seja o eixo x", y="coluna que voce quer que seja o eixo y")

#comando que exibe o gráfico: [Gráfico feito anteriormente].show()


grafico = px.line(tabela, x="Data", y="Temperatura (°C)")

display(grafico) # <- Grafico que será exibido só para mostrar como o comando display() funciona

In [305]:
### Criando os gráficos possíveis em função do tempo ###

for coluna in tabela.columns:
    if coluna == "Data":
        continue
    #comando para fazer a média dos dados de uma coluna (biblioteca: pandas)
    # [base de dados lida anteriormente][coluna].mean()
    # Neste caso: tabela[coluna].mean()

    media = tabela[coluna].mean()


    grafico = px.line(tabela, x="Data", y=coluna, title=f"{coluna} ao decorrer dos dias (Média: {media:.2f})", markers=True)
    
    grafico.update_traces(line=dict(width=3)) # <- Muda a espessura da linha
    grafico.update_layout(template="plotly_dark") # <- Muda a estética do fundo
    grafico.update_layout(xaxis=dict(dtick="D1")) # <- Força a mostrar cada dia
    grafico.show()